let X=200
let Y=21
let Z= X/100 * 21
let A= Z+X


// ejercicio 2

let lado=10
perimetro=10*4
area= lado*lado

// ejercicio 3

let nombre = prompt ("¿Cuál es tu nombre?")
let mensaje =  "hola: " + nombre
alert (mensaje);

// ejercicio 4

let num1= Number (prompt("introduce el número 1: "))
let num2= Number (prompt("introduce el número 2: "))
let num3= Number (prompt("introduce el número 3: "))
let promedio = (num1+num2+num3)/3
alert("el promedio es:", promedio)

// ejercicio 5
 
let km = Number (prompt("introduce los kilómetros recorridos"))
let litrosgs = Number(prompt("introduce los litros consumidos"))
let consumo = (litrosgs/km)
alert ("el consumo es de: " + consumo + "l/KM")

// ejercicio 6

let dato = prompt ("introduce las horas");
let horas = Number.parseInt(dato)
// sin acabar, mirar cesar

// ejercicio 7

let dig2 = Number (prompt("introduce número entre el 10 y el 99: "))
let decenas =  Number.parseInt(dig2/10)
let unidades = Number. parseInt (dig2- decenas * 10)
console.log ( "Dencenas" + decenas )
console.log ( "Unidades" + unidades )
// ejercicio 8

$
